routes/admin.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Http\Controllers\DataTables;
Route::middleware(\App\Http\Middleware\LangMiddleware::class)->group(function () {


    // what did you mean by this....
    // thy just you did'nt make it resource ?? oky

// Messages
    Route::get('/messages', 'MessagesController@index')->name('messages.index');
    Route::get('/messages/create', 'MessagesController@create')->name('messages.create');
    Route::get('/messages/show/{message}', 'MessagesController@show')->name('messages.show');

    Route::post('/messages/create', 'MessagesController@store')->name('messages.store');

    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/logout', 'AdminController@logout')->name('admin.logout');
    Route::get('/lang/{lang}', 'AdminController@changeLang')->name('admin.changeLang');

    // users
    Route::resource('users', 'UsersController');
    Route::post('users/multi_delete', 'UsersController@multi_delete')->name('users.multi_delete');

    // users
    Route::resource('posts', 'PostsController');
    Route::post('posts/multi_delete', 'PostsController@multi_delete')->name('posts.multi_delete');

    // roles and permissions
    Route::resource('roles', 'RoleController');
    Route::post('/roles/multi_delete', 'RoleController@multi_delete')->name('roles.multi_delete');

    Route::resource('permissions', 'PermissionController');
    Route::post('permissions/multi_delete', 'PermissionController@multi_delete')->name('permissions.multi_delete');

    // Routes Goes Here
});

routes/web.php
<?php

Route::get('/','PagesController@index')->name('index');
Route::get('{post}','PagesController@show')->name('index.show');

Route::get('contact','PagesController@contact')->name('contact_us');
Route::get('about','PagesController@about')->name('about_us');

Auth::routes();
// Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/posts (copy)/Postsdashboard.blade.php
@extends('backend.theme.layout.app')
@section('styles')
    <link rel="stylesheet" href="{{asset('backend/datatables/dataTables.bootstrap-rtl.min.css')}}">
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject bold font-blue-casablanca uppercase"> {{ $title = 'all posts' }} </span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">
                            {{-- {!! $dataTable->table(['class'=> 'table table-striped table-bordered table-hover'], true) !!} --}}
<table id='users-table' class="table">
  <thead>
      <tr>
        <td>id</td>
          <td>title</td>
          <td>content</td>
          <td>status</td>
          {{-- <td>user_id</td> --}}
          <td>created_at</td>
          <td>updated_at</td>
          <td>edit</td>
          <td>delete</td>
      </tr>
  </thead>
</table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
  <script src="{{asset('backend/datatables/dataTables.min.js')}}"></script>
    <script src="https://datatables.yajrabox.com/js/jquery.min.js"></script>
  <script src="https://datatables.yajrabox.com/js/bootstrap.min.js"></script>
  <script src="https://datatables.yajrabox.com/js/jquery.dataTables.min.js"></script>
  <script src="https://datatables.yajrabox.com/js/datatables.bootstrap.js"></script>

  <script type="text/javascript">
      $(function() {
          $('#users-table').DataTable({
              processing: true,
              serverSide: true,
              ajax: 'http://127.0.0.1:8000/admin/Posts/Posts_get_data_table',
              columns:[
                {data:'id'},
                {data:'title'},
                {data:'content'},
                {data:'status'},
                // {data:'user_id'},
                {data:'created_at'},
                {data:'updated_at'},
              ]
          });
      });
  </script>
@endsection

resources/views/backend/posts (copy)/create_post.blade.php
@extends('backend.theme.layout.app')

@section('styles')
    @include('backend.users.incs._styles')
@endsection

@section('content')


    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                      <span class="caption-subject bold uppercase font-blue">{{ $title = 'create post'}}</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-icon-only btn-default" href="" data-toggle="tooltip" title="{{ trans('main.show-all') }}   {{ trans('main.users') }}"> <i class="fa fa-list"></i> </a>
                    </div>
                </div>

                <div class="portlet-body form">
                    <form method="post" action="{{ route('posts.store') }}" class="form-horizontal" role="form" enctype="multipart/form-data">
                        @csrf
                      <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">

                          <label class="col-md-2 control-label">title <span class="required"></span> </label>

                          <div class="col-md-6">
                              <input type="text" name="title"   class="form-control" placeholder="title" required>

                              @if ($errors->has('type'))
                                  <span class="help-block">
                                      <strong class="help-block">{{ $errors->first('title') }}</strong>
                                  </span>

                              @endif
                          </div>
                      </div>
                      <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                          <label class="col-md-2 control-label">post status<span class="required"></span> </label>
                          <div class="col-md-6">
                              <select class="form-control"  name="status">
                                  <option value=""></option>
                                    <option value="1">publish</option>
                                    <option value="0">unpublish</option>
                              </select>
                              @if ($errors->has('type'))
                                  <span class="help-block">
                                      <strong class="help-block">{{ $errors->first('type') }}</strong>
                                  </span>
                              @endif
                          </div>
                      </div>
                      <input type="hidden" name="user_id" value="{{auth()->user()->id}}">
                      <div class="form-group">
                        <label for="Textarea1">content</label>
                        <textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
                      </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-2 col-md-10">
                                    <button type="submit" class="btn green">{{ trans('main.add') }} {{ trans('main.user') }}</button>
                                    <a href="" class="btn default">{{ trans('main.cancel') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/posts (copy)/show.blade.php
@extends('backend.theme.layout.app')

@section('styles')
    @include('backend.users.incs._styles')
    <link rel="stylesheet" href="{{asset('backend/messages/style.css')}}">
@endsection

@section('content')
  <span class="caption-subject bold uppercase font-blue">{{ $title = $message->msg_subject}}</span>
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-body form">
                  <div class="container">
	                   <div class="row">
		                    <section class="content">
                  			<div class="col-md-8">
                          <div class="pull-left">
                            {{$message->created_at}}
                          </div>
                          <hr>
                              <div class="panel panel-default">
                                <div class="panel-heading">
                                  <img class="img-circle" style="width: 43px;" src="{{ ShowImage($message_from->image) }}" alt="user-image">
                                  {{$message_from->name}}
                                </div>
                                <div class="panel-body">
                                  {{$message->msg_body}}
                                </div>
                              </div>
                          <hr>
                        </div>
		                   </section>
	                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script src="{{asset('backend/messages/style.js')}}"></script>
@endsection