routes/admin.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Http\Controllers\DataTables;
Route::middleware(\App\Http\Middleware\LangMiddleware::class)->group(function () {


    // what did you mean by this....
    // thy just you did'nt make it resource ?? oky

// Messages
    Route::get('/messages', 'MessagesController@index')->name('messages.index');
    Route::get('/messages/create', 'MessagesController@create')->name('messages.create');
    Route::get('/messages/show/{message}', 'MessagesController@show')->name('messages.show');

    Route::post('/messages/create', 'MessagesController@store')->name('messages.store');

    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('/logout', 'AdminController@logout')->name('admin.logout');
    Route::get('/lang/{lang}', 'AdminController@changeLang')->name('admin.changeLang');

    // users
    Route::resource('users', 'UsersController');
    Route::post('users/multi_delete', 'UsersController@multi_delete')->name('users.multi_delete');

    // users
    Route::resource('posts', 'PostsController');
    Route::post('posts/multi_delete', 'PostsController@multi_delete')->name('posts.multi_delete');

    // roles and permissions
    Route::resource('roles', 'RoleController');
    Route::post('/roles/multi_delete', 'RoleController@multi_delete')->name('roles.multi_delete');

    Route::resource('permissions', 'PermissionController');
    Route::post('permissions/multi_delete', 'PermissionController@multi_delete')->name('permissions.multi_delete');

    // Routes Goes Here
});

routes/web.php
<?php

Route::get('/','PagesController@index')->name('index');
Route::get('{post}','PagesController@show')->name('index.show');

Route::get('contact','PagesController@contact')->name('contact_us');
Route::get('about','PagesController@about')->name('about_us');

Auth::routes();
// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\DataTables\RolesDatatable;
use App\DataTables\UserRolesDataTable;
use Validator;

class RoleController extends Controller
{
    public function index(RolesDatatable $dataTable)
    {
        return $dataTable->render('backend.roles.index', ['title' => trans('main.show-all').' '.trans('main.roles')]);
    }

    public function create()
    {
        $permissions = Permission::all(); //Get all permissions
        return view('backend.roles.create', [
            'title' => trans('main.role_name'),
            'permissions' => $permissions
        ]);
    }

    public function store(Request $request)
    {
        $rules = [
             'name'         => 'required|unique:roles',
             'permissions'  => 'required',
         ];
        $validator = Validator::make($request->all(), $rules);
        $validator->SetAttributeNames([
             'name'         => trans('main.role_name'),
             'permissions'  => trans('main.permissions')
         ]);
        if ($validator->fails()) {
            return back()->withInput()->withErrors($validator);
        }
        $name = $request['name'];
        $role = new Role();
        $role->name = $name;
        if (array_search('Admin', $request['permissions'])) { // returns false if not found
            $permissions = array_except($request['permissions'], array_search('Admin', $request['permissions']));
        } else {
            $permissions = $request['permissions'];
        }
        $role->save();
        if ($role->name === 'Admin') {
            $role->syncPermissions(Permission::all());
        } else {
            //Looping thru selected permissions
            foreach ($permissions as $permission) {
                if (Permission::find($permission)) {
                    $p = Permission::where('id', '=', $permission)->firstOrFail();
                    //Fetch the newly created role and assign permission
                    $role = Role::where('name', '=', $name)->first();
                    $role->givePermissionTo($p);
                }
            }
        }


        // get thye user permissions depinding on then roles
        $permissions = auth()->user()->getAllPermissions()->pluck('name')->toArray();
        // save the persdissions to can Chack on the persissions
        session()->put('user.permissions', $permissions);


        session()->flash('success', trans('main.added-message'));
        return redirect()->route('roles.index');
    }


    public function show(UserRolesDataTable $dataTable, $id)
    {
        // GetRoleName
        $role = Role::find($id);
        if ($role) {
            return $dataTable->GetRoleName($role->name)->render('backend.roles.show', [
                'title' => trans('main.show-all').' '.trans('main.roles'),
                'show' => $role,
            ]);
        }
        return redirect()->back();
    }


    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();
        return view('backend.roles.edit', [
            'title'       => trans('main.role_name'),
            'role'        => $role,
            'permissions' => $permissions
        ]);
    }


    public function update(Request $request, $id)
    {
        $role = Role::find($id);
        if ($role) {
            if ($role->name == 'Admin') {
                session()->flash('error', trans('main.error-message-role'));
            } else {
                $rules = [
                    'name'         => 'required|unique:roles,name,'.$id.',id',
                    'permissions'  => 'required',
                ];
                $validator = Validator::make($request->all(), $rules);
                $validator->SetAttributeNames([
                    'name'         => trans('main.role_name'),
                    'permissions'  => trans('main.permisions')
                ]);
                if ($validator->fails()) {
                    return back()->withInput()->withErrors($validator);
                }
                $input = $request->except(['permissions']);
                $permissions = $request['permissions'];
                $role->fill($input)->save();
                $p_all = Permission::all(); //Get all permissions

                foreach ($p_all as $p) {
                    $role->revokePermissionTo($p); //Remove all permissions associated with role
                }

                foreach ($permissions as $permission) {
                    $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
                    $role->givePermissionTo($p);  //Assign permission to role
                }

                // get thye user permissions depinding on then roles
                $permissions = auth()->user()->getAllPermissions()->pluck('name')->toArray();
                // save the persdissions to can Chack on the persissions
                session()->put('user.permissions', $permissions);

                session()->flash('success', trans('main.updated'));
            }
            return redirect()->route('roles.index');
        }
        return back()->withErrors(['There Is Some Error']);
    }


    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        if ($role) {
            if ($role->name == 'Admin') {
                session()->flash('error', trans('main.error-message-role'));
            } else {
                session()->flash('success', trans('main.deleted-message'));
                $role->delete();
            }
        }

        // get thye user permissions depinding on then roles
        $permissions = auth()->user()->getAllPermissions()->pluck('name')->toArray();
        // save the persdissions to can Chack on the persissions
        session()->put('user.permissions', $permissions);

        return redirect()->route('roles.index');
    }
}

resources/views/backend/roles/create.blade.php
@extends('backend.theme.layout.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject bold uppercase font-blue">{{$title}}</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-icon-only btn-default" href="{{route('roles.index')}}" data-toggle="tooltip" title="{{trans('main.show-all')}}   {{trans('main.roles')}}"> <i class="fa fa-list"></i> </a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form method="post" action="{{ route('roles.store') }}" class="form-horizontal" role="form" enctype="multipart/form-data">
                        @csrf
                        <div class="form-body">
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="name">{{trans('main.role_name')}}</label>
                                <div class="col-md-9">
                                    {!! Form::text('name',old('name'),['class'=>'form-control','placeholder'=>trans('main.role_name')]) !!}
                                </div>
                            </div>

                            <div class='form-group' id="permissions_container">
                                <label class="col-md-3 control-label">{{ trans('main.assign_permissions') }}</label>
                                <div class="col-md-9">
                                    <input type="checkbox" class="select-all" name="permissions[]" onclick="select_all()" value="Admin">
                                     {{ Form::label('All', 'All') }}
                                    <hr>
                                    @foreach ($permissions->chunk(4) as $permissionChunck)
                                        <div class="row">
                                            @foreach ($permissionChunck as $permission)
                                                <div class="col-md-3">
                                                    <input type="checkbox" class="selected_data" name="permissions[]" value="{{ $permission->id }}">
                                                    {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>
                                                </div>
                                            @endforeach
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button type="submit" class="btn green">{{ trans('main.add') }} {{ trans('main.role') }}</button>
                                    <a href="{{ route('roles.index') }}" class="btn default">{{ trans('main.cancel') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/roles/edit.blade.php
@extends('backend.theme.layout.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject bold uppercase font-blue">{{$title}}</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-icon-only btn-default" href="{{route('roles.index')}}" data-toggle="tooltip" title="{{trans('main.show-all')}}   {{trans('main.roles')}}"> <i class="fa fa-list"></i> </a>
                    </div>
                </div>
                <div class="portlet-body form">
                    {!! Form::model($role, ['route' => array('roles.update', $role->id), 'method' => 'PUT','class'=>'form-horizontal']) !!}
                        <div class="form-body">
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="name">{{trans('main.role_name')}}</label>
                                <div class="col-md-9">
                                    {!! Form::text('name',null,['class'=>'form-control','placeholder'=>trans('main.role_name')]) !!}
                                </div>
                            </div>
                            <div class='form-group'>
                                <label class="col-md-3 control-label">{{ trans('main.assign_permissions') }}</label>
                                <div class="col-md-9">
                                    @foreach ($permissions->chunk(4) as $permissionChunck)
                                        <div class="row">
                                            @foreach ($permissionChunck as $permission)
                                                <div class="col-md-3">
                                                    {{ Form::checkbox('permissions[]',  $permission->id ) }}
                                                    {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>
                                                </div>
                                            @endforeach
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <button type="submit" class="btn green">{{ trans('main.edit') }} {{ trans('main.role') }}</button>
                                    <a href="{{ route('roles.index') }}" class="btn default">{{ trans('main.cancel') }}</a>
                                </div>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/roles/index.blade.php
@extends('backend.theme.layout.app')

@section('styles')
    <link rel="stylesheet" href="{{asset('backend/datatables/dataTables.bootstrap-'.GetDirection().'.min.css')}}">
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <form method="post" action="{{ route('roles.multi_delete') }}">
                @csrf
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <span class="caption-subject bold font-blue-casablanca uppercase"> {{ $title }} </span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                {!! $dataTable->table(['class'=> 'table table-striped table-bordered table-hover'], true) !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="multi_delete">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button class="close" data-dismiss="modal">x</button>
                                <h4 class="modal-title">{{trans('main.delete')}} </h4>
                            </div>
                            <div class="modal-body">
                                <div class="delete_done"> {{trans('main.ask-delete')}} <span id="count"></span> {{trans('main.record')}} ! </div>
                                <div class="check_delete">{{trans('main.check-delete')}}</div>
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-danger delete_done" type="submit">{{ trans('main.approval') }}</button>
                                <a class="btn btn-default" data-dismiss="modal">{{trans('main.cancel')}}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('backend/datatables/dataTables.min.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(window).keydown(function(event){
                if(event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });
        });
        $(document).on('click', '.createBtn', function() {
            window.location = "{{ route('roles.create') }}";
        });
        $(document).on('click', '.deleteBtn', function() {
            $('#multi_delete').modal('show');
            var number_checkbox = $(".selected_data").filter(":checked").length;
            $('#count').html(number_checkbox);
            if(number_checkbox > 0){
                $('.delete_done').show();
                $('.check_delete').hide();
            }else{
                $('.delete_done').hide();
                $('.check_delete').show();
            }
        });
    </script>
    {!! $dataTable->scripts() !!}
@endsection

resources/views/backend/roles/show.blade.php
@extends('backend.theme.layout.app')

@section('styles')
    <link rel="stylesheet" href="{{asset('backend/datatables/dataTables.bootstrap.min.css')}}">
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <form method="post" action="{{ route('roles.multi_delete') }}">
                @csrf
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <span class="caption-subject bold font-blue-casablanca uppercase"> {{ $title }} </span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                {!! $dataTable->table(['class'=> 'table table-striped table-bordered table-hover'], true) !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="multi_delete">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button class="close" data-dismiss="modal">x</button>
                                <h4 class="modal-title">{{trans('main.delete')}} </h4>
                            </div>
                            <div class="modal-body">
                                <div class="delete_done"> {{trans('main.ask-delete')}} <span id="count"></span> {{trans('main.record')}} ! </div>
                                <div class="check_delete">{{trans('main.check-delete')}}</div>
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-danger delete_done" type="submit">{{ trans('main.approval') }}</button>
                                <a class="btn btn-default" data-dismiss="modal">{{trans('main.cancel')}}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light">
                <div class="portlet-body">
                    <div class="row">
                        @foreach ($show->permissions()->pluck('name')->chunk(4) as $Chunkedvalue)
                            <div class="col-md-4">
                                <ul class="list-group">
                                    @foreach ($Chunkedvalue as $val)
                                        <li class="list-group-item">{{ $val }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('backend/datatables/dataTables.min.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(window).keydown(function(event){
                if(event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });
        });
        $(document).on('click', '.createBtn', function() {
            window.location = "{{ route('roles.create') }}";
        });
        $(document).on('click', '.deleteBtn', function() {
            $('#multi_delete').modal('show');
            var number_checkbox = $(".selected_data").filter(":checked").length;
            $('#count').html(number_checkbox);
            if(number_checkbox > 0){
                $('.delete_done').show();
                $('.check_delete').hide();
            }else{
                $('.delete_done').hide();
                $('.check_delete').show();
            }
        });
    </script>
    {!! $dataTable->scripts() !!}
@endsection